name = "gr8r-airtable-worker"
main = "index.js"
compatibility_date = "2025-06-12"

routes = [
  { pattern = "api.gr8r.com/api/airtable*", zone_name = "gr8r.com" }
]

[[services]]
binding = "GRAFANA_WORKER"
service = "gr8r-grafana-worker"
environment = "production"
